server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ENC(8wXgU9bsE17cYyRV8ppdA5IoAucJdUeeNnZtJdw1nYo+f5FsL6ydM31xD8XpIStYGh9i7SbKc44nJ9E3edEJ0LIMiOfbCjEdyoDqjp2CN7iGa/O6ih8/Pb1Fq+snhUzUs5wzkZ+9SP6rAVl8BiwQ5B+NaQXR0bqm/QnjTzk+kigeeVtUngIkBHlOYhv9j2a4RITfaMdmVAkzbjk1Zk/j1g==)
    username: ENC(kSbVij29Q5IxlMTyH1g0rw==)
    password: ENC(f2DZKexIllOKp9G6wKa2T+E/dqGcnngS)
    driver-class-name: com.mysql.cj.jdbc.Driver

jasypt:
  encryptor:
    password: ${encrypt_key}
